# Copyright (c) Forward Email LLC
# SPDX-License-Identifier: BUSL-1.1

---
# - name: Import security playbook
#   import_playbook: security.yml
# - name: Import Node.js playbook
#   import_playbook: node.yml
- name: Import SSH keys playbook
  import_playbook: ssh-keys.yml
- hosts: bree
  connection: local
  name: Hostname
  become: true
  become_user: root
  tasks:
    - name: Set hostname
      hostname:
        name: "{{ lookup('env', 'BREE_HOST') }}"
- hosts: bree
  connection: local
  name: Bree
  become: true
  become_user: root
  tasks:
    # ufw
    - name: Enable ufw
      ufw:
        state: enabled
        policy: deny
        direction: incoming
    - name: Limit ufw ssh
      ufw:
        rule: limit
        port: 22
        proto: tcp
    - name: Allow ssh
      ufw:
        rule: allow
        port: 22
        proto: tcp
    - name: Reload ufw
      ufw:
        state: reloaded
